name: gp1_mvp
description: "GoJobs - Jordan Job Finding App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.6.0

  # UI / Fonts
  google_fonts: ^6.2.1

  # Local Storage
  shared_preferences: ^2.3.2

  http: ^1.2.0

  # Network Images
  cached_network_image: ^3.4.1

  # File Picking (CV/Resume upload)
  file_picker: ^8.0.0

  # Image Picking (Portfolio photos)
  image_picker: ^1.1.2

  # Localization
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile_pic.png
    - assets/images/company_logo.png
    - assets/images/woman_banner.png
    - assets/images/calmalocationn.png
    - assets/images/Group75.png
    - assets/images/Group67.png
    - assets/images/undraw_messagelogo.png
    - assets/images/nosavings.png