name: Non-Functional - Flutter Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Formatting (Non-functional)
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Code Quality (Non-functional)
        run: flutter analyze