name: Non-Functional - Code Health & Maintainability

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  health-audit:
    name: Maintainability Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install Dependencies
        run: flutter pub get

      - name: Code Quality Scan (Reliability)
        # checks code for memory leaks andd perormance issues 
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Dependency Health Audit (Maintainability)
        # looks for old packages 
        run: flutter pub outdated